dcolumn/test_app/urls.py
#
# dcolumn/test_app/urls.py
#

from django.urls import re_path, path

from . import views


urlpatterns = [
    path('test-book-create/', views.test_book_create_view,
         name='test-book-create'),
    re_path(r'^test-book-update/(?P<pk>\d+)/$', views.test_book_update_view,
        name='test-book-update'),
    re_path(r'^test-book-detail/(?P<pk>\d+)/$', views.test_book_detail_view,
        name='test-book-detail'),
    path('test-book-list/', views.test_book_list_view,
         name='test-book-list'),
    ]

dcolumn/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

from dcolumn import settings


urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^parent/', include('dcolumn.dynamic_columns.urls')),
    )

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^dev/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_URL, 'show_indexes': True}),
        #url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        #    {'document_root': settings.MEDIA_ROOT}),
        )
else:
    urlpatterns += patterns(
        '',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_URL, 'show_indexes': True}),
        )

dcolumn/dynamic_columns/models.py
#
# dcolumn/dynamic_columns/models.py
#

import logging
from collections import OrderedDict

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse

from dcolumn.common.model_mixins import (
    UserModelMixin, TimeModelMixin, StatusModelMixin, StatusModelManagerMixin)
from .choices import Language
from .manager import dcolumn_manager

log = logging.getLogger('dcolumn.models')


#
# Book
#
class BookManager(StatusModelManagerMixin):

    def dynamic_column(self):
        return self.active()


class Book(UserModelMixin, TimeModelMixin, StatusModelMixin):
    title = models.TextField(
        verbose_name=_("Title"), help_text=_("Enter a book title."))
    author = models.TextField(
        verbose_name=_("Author"), help_text=_("Enter the author of this book."))
    publisher = models.TextField(
        verbose_name=_("Publisher"),
        help_text=_("Enter the publisher of this book."))
    isbn10 = models.TextField(
        verbose_name=_("ISBN-10"), null=True, blank=True,
        help_text=_("Enter the book ISBN-10 code."))
    isbn13 = models.TextField(
        verbose_name=_("ISBN-13"), help_text=_("Enter the book ISBN-13 code."))

    objects = BookManager()

    class Meta:
        verbose_name = _("Book")
        verbose_name_plural = _("Books")

    def __unicode__(self):
        return self.title

dcolumn_manager.register_choice(Book, 2, u'title')


#
# DynamicColumn
#
class DynamicColumnManager(StatusModelManagerMixin):

    def get_fk_slugs(self):
        result = {}

        for record in self.active():
            if record.value_type == self.model.CHOICE:
                name = dcolumn_manager.choice_relation_map.get(record.relation)
                result[name] = record.slug

        return result


class DynamicColumn(UserModelMixin, TimeModelMixin, StatusModelMixin):
    BOOLEAN = 1
    CHOICE = 2
    DATE = 3
    FLOAT = 4
    NUMBER = 5
    TEXT = 6
    TEXT_BLOCK = 7
    VALUE_TYPES = (
        (BOOLEAN, _("Boolean")),
        (CHOICE, _("Choice")),
        (DATE, _("Date")),
        (FLOAT, _("Floating Point")),
        (NUMBER, _("Number")),
        (TEXT, _("Text")),
        (TEXT_BLOCK, _("Text Block")),
        )
    VALUE_TYPES_MAP = dict(VALUE_TYPES)
    NO = False
    YES = True
    YES_NO = (
        (NO, _("No")),
        (YES, _("Yes"))
        )

    name = models.TextField(
        verbose_name=_("Name"), help_text=_("Enter a column name."))
    slug = models.SlugField(verbose_name=_("Slug"), editable=False)
    value_type = models.IntegerField(
        verbose_name=_("Value Type"), choices=VALUE_TYPES,
        help_text=_("Choose the value type."))
    relation = models.IntegerField(
        verbose_name=_("Choice Relation"),
        choices=dcolumn_manager.choice_relation,
        null=True, blank=True, help_text=_("Choose the Choice Relation type."))
    required = models.BooleanField(
        verbose_name=_("Required Field"), choices=YES_NO, default=NO,
        help_text=_("If this field is required based on business rules then "
                    "choose 'Yes'."))
    store_relation = models.BooleanField(
        verbose_name=_("Store Relation Value"), choices=YES_NO, default=NO,
        help_text=_("Store the literal value not the primary key of the "
                    "relation (used when choices change often). The most "
                    "common usage is the default 'No', to not store."))
    location = models.IntegerField(
        verbose_name=_("Display Location"),
        choices=dcolumn_manager.css_containers,
        help_text=_("Choose a display location."))
    order = models.PositiveSmallIntegerField(verbose_name='Display Order')

    objects = DynamicColumnManager()

    class Meta:
        ordering = ('location', 'order', 'name',)
        verbose_name = _("Dynamic Column")
        verbose_name_plural = _("Dynamic Columns")

    def save(self):
        self.slug = slugify(self.name)
        super(DynamicColumn, self).save()

    def __unicode__(self):
        return self.name

    def _relation_producer(self):
        result = ''

        if self.relation is not None:
            result = dcolumn_manager.choice_relation_map.get(self.relation, '')

        return result
    _relation_producer.short_description = _("Relation")


#
# DynamicColumnItem
#
class DynamicColumnItemManager(StatusModelManagerMixin):

    def get_dynamic_columns(self, name):
        try:
            return self.active().get(name=name).dynamic_column.active(
                ).order_by('location', 'order', 'name')
        except self.model.DoesNotExist:
            msg = ("No objects in database, please create initial objects "
                   "for Dynamic Columns and Dynamic Column Items")
            log.error(msg)
            raise self.model.DoesNotExist(msg)

    def serialize_columns(self, obj=None):
        records = self.get_dynamic_columns(
            dcolumn_manager.get_default_column_name(u'Parent'))
        result = OrderedDict()

        if obj:
            key_value_map = obj.serialize_key_value_pairs()

        for record in records:
            rec = result.setdefault(record.pk, {})
            rec[u'name'] = record.name
            rec[u'slug'] = record.slug
            rec[u'value_type'] = record.value_type
            rec[u'relation'] = record.relation
            if record.relation: rec[u'store_relation'] = record.store_relation
            rec[u'required'] = record.required
            # We convert the list to a dict because css_container_map may
            # not be keyed with integers.
            rec[u'location'] = dict(dcolumn_manager.css_containers).get(
                record.location, u'')
            rec[u'order'] = record.order
            if obj: rec[u'value'] = key_value_map.get(record.pk, u'')

        return result

    def get_active_relation_items(self):
        records = self.get_dynamic_columns(
            dcolumn_manager.get_default_column_name(u'Parent'))
        return [dcolumn_manager.choice_relation_map.get(record.relation)
                for record in records if record.relation]


class DynamicColumnItem(UserModelMixin, TimeModelMixin, StatusModelMixin):
    name = models.TextField(
        verbose_name=_("Name"), unique=True,
        help_text=_("Enter a unique name for this record."))
    dynamic_column = models.ManyToManyField(
        DynamicColumn, verbose_name=_("Dynamic Column"),
        related_name='dynamic_column_items')

    objects = DynamicColumnItemManager()

    class Meta:
        verbose_name = _("Dynamic Column Item")
        verbose_name_plural = _("Dynamic Column Items")

    def __unicode__(self):
        return unicode("{}-{}".format(self.name, self.mtime.isoformat()))


#
# Parent (Any model you need to have predefined key/value pairs on.)
#
class ParentManager(StatusModelManagerMixin):
    pass


class Parent(TimeModelMixin, UserModelMixin, StatusModelMixin):
    name = models.TextField(
        verbose_name=_("Name"), unique=True,
        help_text=_("Enter a unique name for this record."))
    dynamic_column_item = models.ForeignKey(
        DynamicColumnItem, verbose_name=_("Dynamic Column Item"),
        help_text=_(u"Choose the version of the dynamic columns you want "
                    u"for all Patents."))

    objects = ParentManager()

    class Meta:
        verbose_name = _("Parent")
        verbose_name_plural = _("Parents")

    def save(self, *args, **kwargs):
        super(Parent, self).save(*args, **kwargs)

    def __unicode__(self):
        return unicode("{}".format(self.name))

    def get_absolute_url(self):
        return reverse('parent-detail', kwargs={'pk': self.pk})

    def serialize_key_value_pairs(self):
        result = {}

        for kv in self.keyvalue_pairs.all():
            result[kv.dynamic_column_id] = kv.value

        return result

    def _detail_producer(self):
        return u'<a href="{}">{}</a>'.format(self.get_absolute_url(), self)
    _detail_producer.short_description = "View Detail"
    _detail_producer.allow_tags = True

    def find_key_value(self, name):
        # FIX ME -- This needs to find the model named with 'name' then return
        # the value of that object, not the hand edited name in the
        # dynamic_column.
        record = self.keyvalue_pairs.filter(dynamic_column__name=name)
        result = u''

        if len(record) > 0:
            result = record[0].value

        return result


#
# KeyValue
#
class KeyValueManager(models.Manager):

    def set_parent_key_value_pairs(self, obj):
        for item in obj.dynamic_column_item.dynamic_column.all():
            self.create(parent=obj, dynamic_column=item)


class KeyValue(models.Model):
    parent = models.ForeignKey(
        Parent, verbose_name=_("Parent"), related_name='keyvalue_pairs')
    dynamic_column = models.ForeignKey(
        DynamicColumn, verbose_name=_("Dynamic Column"),
        related_name='keyvalue_pairs')
    value = models.TextField(verbose_name=_("Value"), null=True, blank=True)

    objects = KeyValueManager()

    class Meta:
        verbose_name = _("Key Value")
        verbose_name_plural = _("Key Values")

    def __unicode__(self):
        return unicode(self.parent)

dcolumn/test_app/forms.py
#
# dcolumn/test_app/forms.py
#

import logging

from django import forms
from django.core.exceptions import ObjectDoesNotExist

from dcolumn.dcolumns.forms import CollectionBaseFormMixin
from dcolumn.dcolumns.models import KeyValue

from example_site.books.choices import Language
from example_site.books.models import Promotion, Author, Book

log = logging.getLogger('tests.test_app.forms')


#
# TestBook
#
class TestBookForm(CollectionBaseFormMixin):
    title = forms.CharField(
        max_length=250, strip=True, required=True)
    test_bool = forms.BooleanField(
        required=False)
    test_choice = forms.ChoiceField(
        required=True)
    test_pseudo_choice = forms.ChoiceField(
        required=False)
    test_store_relation = forms.ChoiceField(
        required=False)
    test_date = forms.DateField(
        required=False)
    test_time = forms.TimeField(
        required=False)
    test_datetime = forms.DateTimeField(
        required=False)
    test_float = forms.FloatField(
        required=False)
    test_integer = forms.IntegerField(
        required=False)
    test_text = forms.CharField(
        max_length=256, strip=True, required=False)
    test_text_block = forms.CharField(
        max_length=2048, strip=True, required=False)
    active = forms.BooleanField(
        required=False)

    def __init__(self, *args, **kwargs):
        super(TestBookForm, self).__init__(*args, **kwargs)
        log.debug("TestBookForm args: %s, kwargs: %s", args, kwargs)
        self.fields['test_choice'].choices = (
            Author.objects.get_choices('name'))
        self.fields['test_pseudo_choice'].choices = (
            Language.objects.get_choices('name'))
        self.fields['test_store_relation'].choices = (
            Promotion.objects.get_choices('name'))
        # Get rid of the annoying colon after every label.
        self.label_suffix = ''
        log.debug("TestBookForm test_choice: %s, test_pseudo_choice: %s, "
                  "test_store_relation: %s",
                  self.fields['test_choice'].choices,
                  self.fields['test_pseudo_choice'].choices,
                  self.fields['test_store_relation'].choices)

    def clean_test_choice(self):
        return self._get_object(Author, 'test_choice')

    def clean_test_pseudo_choice(self):
        return self._get_object(Language, 'test_pseudo_choice')

    def clean_test_store_relation(self):
        return self._get_object(Promotion, 'test_store_relation')

    def _get_object(self, model, field):
        """
        A zero would be the first select option indicating the
        instructions on selecting a choice. Therefore it's not permitted
        on required fields. If the data is correct then try to get the
        object.
        """
        value = self.cleaned_data.get(field, 0)
        is_zero = value in (0, '0', None, '')
        obj = None

        if self.fields[field].required and is_zero:
            msg = _("The value {} is not permitted.").format(value)
            raise forms.ValidationError(msg)

        if not is_zero: # Left blank
            try:
                obj = model.objects.get(pk=value)
            except ObjectDoesNotExist:
                msg = _("Could not find {} with this id {}").format(
                    model.__name__, value)
                raise forms.ValidationError(msg)

        log.debug("Choices--field: %s, value: %s, is_zero: %s, obj: %s",
                  field, value, is_zero, obj)
        return obj

    def clean(self):
        cleaned_data = super(TestBookForm, self).clean()
        log.debug("cleaned_data: %s", cleaned_data)
        return cleaned_data

    class Meta:
        model = Book
        fields = ['title', 'test_bool', 'test_choice', 'test_pseudo_choice',
                  'test_store_relation', 'test_date', 'test_time',
                  'test_datetime', 'test_float', 'test_integer', 'test_text',
                  'test_text_block', 'active',
                  ] + CollectionBaseFormMixin.Meta.fields

dcolumn/test_app/views.py
#
# dcolumn/test_app/views.py
#

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, CreateView, UpdateView, ListView

from dcolumn.dcolumns.views import (
    CollectionCreateUpdateViewMixin, CollectionDetailViewMixin)

from example_site.books.models import Book

from .forms import TestBookForm


#
# TestBookCreateView
#
class TestBookCreateView(LoginRequiredMixin,
                         CollectionCreateUpdateViewMixin,
                         CreateView):
    template_name = 'test_book_create_view.html'
    form_class = TestBookForm
    model = Book

    def get_success_url(self):
        url = reverse('test-book-detail', kwargs={'pk': self.object.pk})
        url += '?created=true'
        return url

test_book_create_view = TestBookCreateView.as_view()


#
# TestBookUpdateView
#
class TestBookUpdateView(LoginRequiredMixin,
                         CollectionCreateUpdateViewMixin,
                         UpdateView):
    template_name = 'test_book_create_view.html'
    form_class = TestBookForm
    model = Book

    def get_success_url(self):
        url = reverse('test-book-detail', kwargs={'pk': self.object.pk})
        url += '?updated=true'
        return url

test_book_update_view = TestBookUpdateView.as_view()


#
# TestBookDetailView
#
class TestBookDetailView(LoginRequiredMixin,
                         CollectionDetailViewMixin,
                         DetailView):
    template_name = 'test_book_detail_view.html'
    model = Book

    def get_context_data(self, **kwargs):
        """
        Get context data for the KeyValue objects.
        """
        context = super(TestBookDetailView, self).get_context_data(**kwargs)
        # Create actions if any.
        book = kwargs.get('object')
        pk = book and book.id or 0
        actions = [
            {'name': 'Create a New Book Entry',
             'url': reverse('test-book-create')},
            {'name': 'Edit this Book Entry',
             'url': reverse('test-book-update', args=(pk,))},
            ]
        context['actions'] = actions
        # Create messages if any.
        info_message = {}

        for flag in ('created', 'updated',):
            info_message[flag] = bool(self.request.GET.get(flag, ''))

        context['info_message'] = info_message
        return context

test_book_detail_view = TestBookDetailView.as_view()


#
# TestBookListView
#
class TestBookListView(LoginRequiredMixin,
                       ListView):
    template_name = 'test_book_list_view.html'
    model = Book
    paginate_by = 50

test_book_list_view = TestBookListView.as_view()

dcolumn/test_app/templates/test_book_create_view.html
{% extends "base.html" %}
{% load autodisplay %}
{% block title %}Book{% endblock %}
{% block head_extras %}{{ form.media }}{% endblock %}
{% block header %}
  <div class="header">
    <h2>Test Book</h2>
  </div>
{% endblock %}
{% block content %}
  <div class="wrapper">
{% if object %}
    <form name="test-book-update" method="post"
          action="{% url 'book-update' object.pk %}">
{% else %}
    <form name="test-book-update" method="post"
          action="{% url 'book-create' %}">
{% endif %}
      {% csrf_token %}
      <div class="container">
        {{ keyvalue_set.management_form }}
        <div id="message">
          {{ form.non_field_errors }}
        </div>
        <div class="dynamic-container {{ css.book_top }}">
          <ul>
            <li>
              {{ form.title.label_tag }}
              {{ form.title.as_widget }}
              {{ form.title.errors }}
            </li>
{% for relation in relations.values %}
{% if relation.location == css.book_top %}
            <li>
              <label for="id-{{ relation.slug }}">{{ relation.name }}</label>
              {% auto_display relation options=dynamicColumns %}
              {% combine_contexts form.errors relation.slug %}
            </li>
{% endif %}
{% endfor %}
          </ul>
        </div>
        <div class="dynamic-container {{ css.book_center }}">
          <ul>
{% for relation in relations.values %}
{% if relation.location == css.book_center %}
            <li>
              <label for="id-{{ relation.slug }}">{{ relation.name }}</label>
              {% auto_display relation options=dynamicColumns %}
              {% combine_contexts form.errors relation.slug %}
            </li>
{% endif %}
{% endfor %}
          </ul>
        </div>
        <div class="dynamic-container {{ css.book_bottom }}">
          <ul>
{% for relation in relations.values %}
{% if relation.location == css.book_bottom %}
            <li>
              <label for="id-{{ relation.slug }}">{{ relation.name }}</label>
              {% auto_display relation options=dynamicColumns %}
              {% combine_contexts form.errors relation.slug %}
            </li>
{% endif %}
{% endfor %}
            <li>
              {{ form.active.label_tag }}
              {{ form.active.as_widget }}
              {{ form.active.errors }}
            </li>
          </ul>
        </div>
      </div> <!-- div.container -->
      <div class="actions">
{% if object %}
        <button type="submit"
                class="book-submit"
                formaction="{% url 'book-update' object.pk %}">Update</button>
{% else %}
        <button type="submit"
                class="book-submit"
                formaction="{% url 'book-create' %}">Save</button>
{% endif %}
      </div> <!-- div.actions -->
    </form>
  </div> <!-- div.wrapper -->
{% endblock %}

dcolumn/test_app/templates/test_book_detail_view.html
{% extends "base.html" %}
{% load autodisplay %}
{% block title %}Book Detail{% endblock %}
{% block header %}
  <div class="header">
    <h2>Book Detail</h2>
    <div class="dashboard">
      <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'author-create' %}">Create Author</a></li>
        <li><a href="{% url 'publisher-create' %}">Create Publisher</a></li>
        <li><a href="{% url 'promotion-create' %}">Create Promotion</a></li>
      </ul>
    </div>
  </div>
{% endblock %}
{% block content %}
  <div class="wrapper">
      <div class="actions">
{% spaceless %}
{% if actions %}
        <ul>
{% for action in actions %}
          <li><a href="{{ action.url }}">{{ action.name }}</a></li>
{% endfor %}
        </ul>        
{% endif %}
{% endspaceless %}
      </div>
      <div class="container">
        <div class="message">
{% if info_message.created %}
          <div>The record has been created and is displayed below.</div>
{% elif info_message.updated %}
          <div>The record has been updated and is displayed below.</div>
{% endif %}
        </div>
        <div class="dynamic-container {{ css.book_top }}">
          <ul>
            <li>
              <label>Title</label>
              <span>{{ object.title }}</span>
            </li>
{% for relation in relations.values %}
{% if relation.location == css.book_top %}
            <li>
              <label>{{ relation.name }}</label>
              {% auto_display relation options=dynamicColumns display=True %}
            </li>
{% endif %}
{% endfor %}
          </ul>
        </div>
        <div class="dynamic-container {{ css.book_center }}">
          <ul>
{% for relation in relations.values %}
{% if relation.location == css.book_center %}
            <li>
              <label>{{ relation.name }}</label>
              {% auto_display relation options=dynamicColumns display=True %}
            </li>
{% endif %}
{% endfor %}
          </ul>
        </div>
        <div class="dynamic-container {{ css.book_bottom }}">
          <ul>
{% for relation in relations.values %}
{% if relation.location == css.book_bottom %}
            <li>
              <label>{{ relation.name }}</label>
              {% auto_display relation options=dynamicColumns display=True %}
            </li>
{% endif %}
{% endfor %}
            <li>
              <label>Active</label>
              <span>{{ object.active|yesno }}</span>
            </li>
          </ul>
        </div>
      </div> <!-- div.container -->
  </div> <!-- div.wrapper -->
{% endblock %}

dcolumn/test_app/templates/test_book_list_view.html
{% extends "base.html" %}
{% load autodisplay %}
{% block title %}Book List{% endblock %}
{% block head_extras %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/list_views.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/list_pagination.css">
{% endblock %}
{% block header %}
  <div class="header">
    <h2>Book List</h2>
    <div class="dashboard">
      <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'author-list' %}">Author List</a></li>
        <li><a href="{% url 'publisher-list' %}">Publisher List</a></li>
        <li><a href="{% url 'promotion-list' %}">Promotion List</a></li>
       </ul>
    </div>
  </div>
{% endblock %}
{% block content %}
{% if object_list %}
  <div class="wrapper">
{% if is_paginated %}
    <div class="actions">
      <div class="list-pagination">
        <ul>{% if page_obj.has_next %}
          <li>
            <a href="{{ uri }}?page={{ paginator.page_range|length }}">>></a>
          </li>
          <li>
            <a href="{{ uri }}?page={{ page_obj.next_page_number }}">></a>
          </li>{% else %}<li>&nbsp;</li><li>&nbsp;</li>{% endif %}
          <li class="list-pagination middle">
            Page {{ page_obj.number }} of {{ paginator.page_range|length }}
          </li>{% if page_obj.has_previous %}
          <li>
            <a href="{{ uri }}?page={{ page_obj.previous_page_number }}"><</a>
          </li>
          <li>
            <a href="{{ uri }}?page={{ paginator.page_range.0 }}"><<</a>
          </li>{% else %}<li>&nbsp;</li><li>&nbsp;</li>{% endif %}
        </ul>
      </div>
    </div>
{% endif %}
    <div class="container">
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>SKU</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Edition</th>
            <th>Published Date</th>
            <th>Copyright Year</th>
            <th>ISBN-10</th>
            <th>ISBN-13</th>
            <th>Language</th>
            <th>Promotion</th>
            <th>Active</th>
          </tr>
        </thead>
        <tbody>
{% for object in object_list %}
          <tr>
            <td>
              <a href="{% url 'book-detail' object.id %}">{{ object.title }}</a>
            </td>
{% single_display object book_sku as sku %}
            <td style="text-align: right;">{{ sku }}</td>
{% single_display object author as author %}
            <td>{{ author }}</td>
{% single_display object publisher as publisher %}
            <td>{{ publisher }}</td>
{% single_display object edition as edition %}
            <td style="text-align: right;">{{ edition }}</td>
{% single_display object published_date as pdate %}
            <td style="text-align: right;">{{ pdate|date:"Y-m-d" }}</td>
{% single_display object copyright_year as cyear %}
            <td style="text-align: right;">{{ cyear }}</td>
{% single_display object isbn10 as isbn10 %}
            <td>{{ isbn10 }}</td>
{% single_display object isbn13 as isbn13 %}
            <td>{{ isbn13 }}</td>
{% single_display object language as language %}
            <td>{{ language }}</td>
{% single_display object promotion as promotion %}
            <td>{{ promotion }}</td>
            <td>{{ object.active|yesno }}</td>
          </tr>
{% endfor %}
        </tbody>
      </table>
    </div> <!-- div.container -->
{% if is_paginated %}
    <div class="actions">
      <div class="list-pagination">
        <ul>{% if page_obj.has_next %}
          <li>
            <a href="{{ uri }}?page={{ paginator.page_range|length }}">>></a>
          </li>
          <li>
            <a href="{{ uri }}?page={{ page_obj.next_page_number }}">></a>
          </li>{% else %}<li>&nbsp;</li><li>&nbsp;</li>{% endif %}
          <li class="list-pagination middle">
            Page {{ page_obj.number }} of {{ paginator.page_range|length }}
          </li>{% if page_obj.has_previous %}
          <li>
            <a href="{{ uri }}?page={{ page_obj.previous_page_number }}"><</a>
          </li>
          <li>
            <a href="{{ uri }}?page={{ paginator.page_range.0 }}"><<</a>
          </li>{% else %}<li>&nbsp;</li><li>&nbsp;</li>{% endif %}
        </ul>
      </div>
    </div>
{% endif %}
  </div> <!-- div.wrapper -->
{% endif %}
{% endblock %}